/* Generated By:JJTree&JavaCC: Do not edit this line. VhdlParserCoreConstants.java */
package net.sourceforge.veditor.parser.vhdl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VhdlParserCoreConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int ABS = 7;
  /** RegularExpression Id. */
  int ACCESS = 8;
  /** RegularExpression Id. */
  int ACROSS = 9;
  /** RegularExpression Id. */
  int AFTER = 10;
  /** RegularExpression Id. */
  int ALIAS = 11;
  /** RegularExpression Id. */
  int ALL = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int ARCHITECTURE = 14;
  /** RegularExpression Id. */
  int ARRAY = 15;
  /** RegularExpression Id. */
  int ASSERT = 16;
  /** RegularExpression Id. */
  int ATTRIBUTE = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int BLOCK = 19;
  /** RegularExpression Id. */
  int BODY = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int BUFFER = 22;
  /** RegularExpression Id. */
  int BUS = 23;
  /** RegularExpression Id. */
  int CASE = 24;
  /** RegularExpression Id. */
  int COMPONENT = 25;
  /** RegularExpression Id. */
  int CONFIGURATION = 26;
  /** RegularExpression Id. */
  int CONTEXT = 27;
  /** RegularExpression Id. */
  int CONSTANT = 28;
  /** RegularExpression Id. */
  int DISCONNECT = 29;
  /** RegularExpression Id. */
  int DOWNTO = 30;
  /** RegularExpression Id. */
  int DEFAULT_T = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int ELSIF = 33;
  /** RegularExpression Id. */
  int END = 34;
  /** RegularExpression Id. */
  int ENTITY = 35;
  /** RegularExpression Id. */
  int EXIT = 36;
  /** RegularExpression Id. */
  int FILE = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int FORCE = 39;
  /** RegularExpression Id. */
  int FUNCTION = 40;
  /** RegularExpression Id. */
  int GENERATE = 41;
  /** RegularExpression Id. */
  int GENERIC = 42;
  /** RegularExpression Id. */
  int GROUP = 43;
  /** RegularExpression Id. */
  int GUARDED = 44;
  /** RegularExpression Id. */
  int IF = 45;
  /** RegularExpression Id. */
  int IMPURE = 46;
  /** RegularExpression Id. */
  int IN = 47;
  /** RegularExpression Id. */
  int INERTIAL = 48;
  /** RegularExpression Id. */
  int INOUT = 49;
  /** RegularExpression Id. */
  int IS = 50;
  /** RegularExpression Id. */
  int LABEL = 51;
  /** RegularExpression Id. */
  int LIBRARY = 52;
  /** RegularExpression Id. */
  int LINKAGE = 53;
  /** RegularExpression Id. */
  int LITERAL = 54;
  /** RegularExpression Id. */
  int LOOP = 55;
  /** RegularExpression Id. */
  int MAP = 56;
  /** RegularExpression Id. */
  int MOD = 57;
  /** RegularExpression Id. */
  int NAND = 58;
  /** RegularExpression Id. */
  int NATURE = 59;
  /** RegularExpression Id. */
  int NEW = 60;
  /** RegularExpression Id. */
  int NEXT = 61;
  /** RegularExpression Id. */
  int NOISE = 62;
  /** RegularExpression Id. */
  int NOR = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int NULL = 65;
  /** RegularExpression Id. */
  int OF = 66;
  /** RegularExpression Id. */
  int ON = 67;
  /** RegularExpression Id. */
  int OPEN = 68;
  /** RegularExpression Id. */
  int OR = 69;
  /** RegularExpression Id. */
  int OTHERS = 70;
  /** RegularExpression Id. */
  int OUT = 71;
  /** RegularExpression Id. */
  int PACKAGE = 72;
  /** RegularExpression Id. */
  int PARAMETER = 73;
  /** RegularExpression Id. */
  int PORT = 74;
  /** RegularExpression Id. */
  int POSTPONED = 75;
  /** RegularExpression Id. */
  int PROCEDURAL = 76;
  /** RegularExpression Id. */
  int PROCEDURE = 77;
  /** RegularExpression Id. */
  int PROCESS = 78;
  /** RegularExpression Id. */
  int PROTECTED = 79;
  /** RegularExpression Id. */
  int PURE = 80;
  /** RegularExpression Id. */
  int QUANTITY = 81;
  /** RegularExpression Id. */
  int RANGE = 82;
  /** RegularExpression Id. */
  int RECORD = 83;
  /** RegularExpression Id. */
  int REGISTER = 84;
  /** RegularExpression Id. */
  int REJECT = 85;
  /** RegularExpression Id. */
  int REM = 86;
  /** RegularExpression Id. */
  int RELEASE = 87;
  /** RegularExpression Id. */
  int REPORT = 88;
  /** RegularExpression Id. */
  int RETURN = 89;
  /** RegularExpression Id. */
  int ROL = 90;
  /** RegularExpression Id. */
  int ROR = 91;
  /** RegularExpression Id. */
  int SELECT = 92;
  /** RegularExpression Id. */
  int SEVERITY = 93;
  /** RegularExpression Id. */
  int SIGNAL = 94;
  /** RegularExpression Id. */
  int SHARED = 95;
  /** RegularExpression Id. */
  int SLA = 96;
  /** RegularExpression Id. */
  int SLL = 97;
  /** RegularExpression Id. */
  int SPECTRUM = 98;
  /** RegularExpression Id. */
  int SRA = 99;
  /** RegularExpression Id. */
  int SRL = 100;
  /** RegularExpression Id. */
  int SUBNATURE = 101;
  /** RegularExpression Id. */
  int SUBTYPE = 102;
  /** RegularExpression Id. */
  int TERMINAL = 103;
  /** RegularExpression Id. */
  int THEN = 104;
  /** RegularExpression Id. */
  int THROUGH = 105;
  /** RegularExpression Id. */
  int TO = 106;
  /** RegularExpression Id. */
  int TOLERANCE = 107;
  /** RegularExpression Id. */
  int TRANSPORT = 108;
  /** RegularExpression Id. */
  int TYPE = 109;
  /** RegularExpression Id. */
  int UNAFFECTED = 110;
  /** RegularExpression Id. */
  int UNITS = 111;
  /** RegularExpression Id. */
  int UNTIL = 112;
  /** RegularExpression Id. */
  int USE = 113;
  /** RegularExpression Id. */
  int VARIABLE = 114;
  /** RegularExpression Id. */
  int WAIT = 115;
  /** RegularExpression Id. */
  int WHEN = 116;
  /** RegularExpression Id. */
  int WHILE = 117;
  /** RegularExpression Id. */
  int WITH = 118;
  /** RegularExpression Id. */
  int XNOR = 119;
  /** RegularExpression Id. */
  int XOR = 120;
  /** RegularExpression Id. */
  int upper_case_letter = 121;
  /** RegularExpression Id. */
  int lower_case_letter = 122;
  /** RegularExpression Id. */
  int digit = 123;
  /** RegularExpression Id. */
  int extended_digit = 124;
  /** RegularExpression Id. */
  int special_character = 125;
  /** RegularExpression Id. */
  int other_special_character = 126;
  /** RegularExpression Id. */
  int format_effector = 127;
  /** RegularExpression Id. */
  int base_specifier_bin_oct_hex = 128;
  /** RegularExpression Id. */
  int base_specifier_dec = 129;
  /** RegularExpression Id. */
  int base_specifier_sign = 130;
  /** RegularExpression Id. */
  int base_specifier = 131;
  /** RegularExpression Id. */
  int underline = 132;
  /** RegularExpression Id. */
  int letter = 133;
  /** RegularExpression Id. */
  int letter_or_digit = 134;
  /** RegularExpression Id. */
  int integer = 135;
  /** RegularExpression Id. */
  int base = 136;
  /** RegularExpression Id. */
  int based_integer = 137;
  /** RegularExpression Id. */
  int based_literal = 138;
  /** RegularExpression Id. */
  int basic_character = 139;
  /** RegularExpression Id. */
  int basic_graphic_character = 140;
  /** RegularExpression Id. */
  int basic_identifier = 141;
  /** RegularExpression Id. */
  int bit_string_literal = 142;
  /** RegularExpression Id. */
  int bit_value = 143;
  /** RegularExpression Id. */
  int character_literal = 144;
  /** RegularExpression Id. */
  int decimal_literal = 145;
  /** RegularExpression Id. */
  int exponent = 146;
  /** RegularExpression Id. */
  int extended_identifier = 147;
  /** RegularExpression Id. */
  int graphic_character = 148;
  /** RegularExpression Id. */
  int string_literal = 149;
  /** RegularExpression Id. */
  int EXP = 150;
  /** RegularExpression Id. */
  int MUL = 151;
  /** RegularExpression Id. */
  int DIV = 152;
  /** RegularExpression Id. */
  int ADD = 153;
  /** RegularExpression Id. */
  int SUB = 154;
  /** RegularExpression Id. */
  int CONCAT = 155;
  /** RegularExpression Id. */
  int EQ = 156;
  /** RegularExpression Id. */
  int NEQ = 157;
  /** RegularExpression Id. */
  int GE = 158;
  /** RegularExpression Id. */
  int LE = 159;
  /** RegularExpression Id. */
  int GT = 160;
  /** RegularExpression Id. */
  int LO = 161;
  /** RegularExpression Id. */
  int MEQ = 162;
  /** RegularExpression Id. */
  int MNEQ = 163;
  /** RegularExpression Id. */
  int MLO = 164;
  /** RegularExpression Id. */
  int MLE = 165;
  /** RegularExpression Id. */
  int MGT = 166;
  /** RegularExpression Id. */
  int MGE = 167;
  /** RegularExpression Id. */
  int SEMICOLON = 168;
  /** RegularExpression Id. */
  int COLON = 169;
  /** RegularExpression Id. */
  int ASSIGN = 170;
  /** RegularExpression Id. */
  int RARROW = 171;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"abs\"",
    "\"access\"",
    "\"across\"",
    "\"after\"",
    "\"alias\"",
    "\"all\"",
    "\"and\"",
    "\"architecture\"",
    "\"array\"",
    "\"assert\"",
    "\"attribute\"",
    "\"begin\"",
    "\"block\"",
    "\"body\"",
    "\"break\"",
    "\"buffer\"",
    "\"bus\"",
    "\"case\"",
    "\"component\"",
    "\"configuration\"",
    "\"context\"",
    "\"constant\"",
    "\"disconnect\"",
    "\"downto\"",
    "\"default\"",
    "\"else\"",
    "\"elsif\"",
    "\"end\"",
    "\"entity\"",
    "\"exit\"",
    "\"file\"",
    "\"for\"",
    "\"force\"",
    "\"function\"",
    "\"generate\"",
    "\"generic\"",
    "\"group\"",
    "\"guarded\"",
    "\"if\"",
    "\"impure\"",
    "\"in\"",
    "\"inertial\"",
    "\"inout\"",
    "\"is\"",
    "\"label\"",
    "\"library\"",
    "\"linkage\"",
    "\"literal\"",
    "\"loop\"",
    "\"map\"",
    "\"mod\"",
    "\"nand\"",
    "\"nature\"",
    "\"new\"",
    "\"next\"",
    "\"noise\"",
    "\"nor\"",
    "\"not\"",
    "\"null\"",
    "\"of\"",
    "\"on\"",
    "\"open\"",
    "\"or\"",
    "\"others\"",
    "\"out\"",
    "\"package\"",
    "\"parameter\"",
    "\"port\"",
    "\"postponed\"",
    "\"procedural\"",
    "\"procedure\"",
    "\"process\"",
    "\"protected\"",
    "\"pure\"",
    "\"quantity\"",
    "\"range\"",
    "\"record\"",
    "\"register\"",
    "\"reject\"",
    "\"rem\"",
    "\"release\"",
    "\"report\"",
    "\"return\"",
    "\"rol\"",
    "\"ror\"",
    "\"select\"",
    "\"severity\"",
    "\"signal\"",
    "\"shared\"",
    "\"sla\"",
    "\"sll\"",
    "\"spectrum\"",
    "\"sra\"",
    "\"srl\"",
    "\"subnature\"",
    "\"subtype\"",
    "\"terminal\"",
    "\"then\"",
    "\"through\"",
    "\"to\"",
    "\"tolerance\"",
    "\"transport\"",
    "\"type\"",
    "\"unaffected\"",
    "\"units\"",
    "\"until\"",
    "\"use\"",
    "\"variable\"",
    "\"wait\"",
    "\"when\"",
    "\"while\"",
    "\"with\"",
    "\"xnor\"",
    "\"xor\"",
    "<upper_case_letter>",
    "<lower_case_letter>",
    "<digit>",
    "<extended_digit>",
    "<special_character>",
    "<other_special_character>",
    "<format_effector>",
    "<base_specifier_bin_oct_hex>",
    "<base_specifier_dec>",
    "<base_specifier_sign>",
    "<base_specifier>",
    "\"_\"",
    "<letter>",
    "<letter_or_digit>",
    "<integer>",
    "<base>",
    "<based_integer>",
    "<based_literal>",
    "<basic_character>",
    "<basic_graphic_character>",
    "<basic_identifier>",
    "<bit_string_literal>",
    "<bit_value>",
    "<character_literal>",
    "<decimal_literal>",
    "<exponent>",
    "<extended_identifier>",
    "<graphic_character>",
    "<string_literal>",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"&\"",
    "\"=\"",
    "\"/=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"?=\"",
    "\"?/=\"",
    "\"?<\"",
    "\"?<=\"",
    "\"?>\"",
    "\"?>=\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"=>\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\'\"",
    "\"|\"",
    "\"<>\"",
    "\"<<\"",
    "\">>\"",
    "\"@\"",
    "\".\"",
    "\"^\"",
    "\"==\"",
  };

}
