/* Generated By:JJTree: Do not edit this line. ASTcontext_reference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTcontext_reference extends SimpleNode {
  public ASTcontext_reference(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=e8725cd6819a64ae1ade1231b1b9966f (do not edit this line) */
