/* Generated By:JJTree: Do not edit this line. ASTcontext_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTcontext_declaration extends SimpleNode {
  public ASTcontext_declaration(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=542a10cdf536968cae635065a8a9b984 (do not edit this line) */
