/* Generated By:JJTree: Do not edit this line. ASTinterface_procedure_specification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_procedure_specification extends SimpleNode {
  public ASTinterface_procedure_specification(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=ef9179af6705c75f65e17596b001ef25 (do not edit this line) */
