/* Generated By:JJTree: Do not edit this line. ASTinterface_package_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_package_declaration extends SimpleNode {
  public ASTinterface_package_declaration(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=1323f1b39f2df7aa75fd7e923d861596 (do not edit this line) */
