/* Generated By:JJTree: Do not edit this line. ASTinterface_subprogram_specification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_subprogram_specification extends SimpleNode {
  public ASTinterface_subprogram_specification(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=8cbd8f756f0703c821273d0e4aaeaee7 (do not edit this line) */
