/* Generated By:JJTree: Do not edit this line. ASTinterface_package_generic_map_aspect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_package_generic_map_aspect extends SimpleNode {
  public ASTinterface_package_generic_map_aspect(int id) {
    super(id);
  }


}
/* JavaCC - OriginalChecksum=a2a62354406d6e355aa50e3f422c4b88 (do not edit this line) */
