/* Generated By:JJTree: Do not edit this line. ASTinterface_subprogram_default.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_subprogram_default extends SimpleNode {
  public ASTinterface_subprogram_default(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=141d0a09b7ee629172cd63b573842230 (do not edit this line) */
