/* Generated By:JJTree: Do not edit this line. ASTinterface_function_specification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_function_specification extends SimpleNode {
  public ASTinterface_function_specification(int id) {
    super(id);
  }
}
/* JavaCC - OriginalChecksum=c2de733b1649a0ff68d4c170365a9d50 (do not edit this line) */
