/* Generated By:JJTree: Do not edit this line. ASTinterface_subprogram_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTinterface_subprogram_declaration extends SimpleNode {
  public ASTinterface_subprogram_declaration(int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=bd2d1681d0df12dd2d9fe41580d121e5 (do not edit this line) */
